### ISSUE TITLE
Blender 2.8

### ISSUE THREAD

**Issue by hansnolte** [LesFeesSpeciales/animation_animall#1]
Hi PiOverFour,
the "keying only selected points for lattices" is such a great feature, please, port it to Blender 2.8.

Many greetings
Hans

**Comment by hansnolte** [comment]
Hi PiOverFour,

many thanks for your answer.
I'm really looking forward to your new version.

Many greetings
Hans

**Comment by PiOverFour** [comment]
Hi @hansnolte,
finally got around to updating it, since the Blender Foundation has apparently not done it. It should work mostly the same, known bugs included. Please see the [blender28](https://github.com/LesFeesSpeciales/animation_animall/tree/blender28) branch.
The lattices seem not to be evaluated properly in object mode though, even though the keyframes exist. If you still use it for lattices, I believe you should use shape keys instead.
I did some minor cleanup while I was at it.

**Comment by hansnolte** [comment]
Hi PiOverFour,
this is so great!
Thank you very much.

Many greetings
Hans
